//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NP.Resources.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} for field {1} is already exists..
        /// </summary>
        public static string AlreadyExistsValueForField {
            get {
                return ResourceManager.GetString("AlreadyExistsValueForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is already in the {0} state..
        /// </summary>
        public static string AlreadyInState {
            get {
                return ResourceManager.GetString("AlreadyInState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} for field {1} is duplicate..
        /// </summary>
        public static string DuplicateValueForField {
            get {
                return ResourceManager.GetString("DuplicateValueForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification key has been expired..
        /// </summary>
        public static string ExpiredVerificationKey {
            get {
                return ResourceManager.GetString("ExpiredVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of field {0} is not in correct format..
        /// </summary>
        public static string FormatNotMatched {
            get {
                return ResourceManager.GetString("FormatNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for date field {0} can not be in the future..
        /// </summary>
        public static string InvalidCurrentDateField {
            get {
                return ResourceManager.GetString("InvalidCurrentDateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of email is invalid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for date field {0} must be in the future..
        /// </summary>
        public static string InvalidFutureDateField {
            get {
                return ResourceManager.GetString("InvalidFutureDateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input data is invalid..
        /// </summary>
        public static string InvalidInputData {
            get {
                return ResourceManager.GetString("InvalidInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the field {0} must be {1}.
        /// </summary>
        public static string InvalidLengthField {
            get {
                return ResourceManager.GetString("InvalidLengthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid record has been selected..
        /// </summary>
        public static string InvalidRecord {
            get {
                return ResourceManager.GetString("InvalidRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route value is not valid for the resource {0}.
        /// </summary>
        public static string InvalidRouteForResource {
            get {
                return ResourceManager.GetString("InvalidRouteForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the field {0} is invalid..
        /// </summary>
        public static string InvalidValueForField {
            get {
                return ResourceManager.GetString("InvalidValueForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification key is invalid..
        /// </summary>
        public static string InvalidVerificationKey {
            get {
                return ResourceManager.GetString("InvalidVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the field {0} is not in range..
        /// </summary>
        public static string LengthNotInRangeField {
            get {
                return ResourceManager.GetString("LengthNotInRangeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of field {0} must be maximum {1}..
        /// </summary>
        public static string LengthTooLongForField {
            get {
                return ResourceManager.GetString("LengthTooLongForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record does not exist..
        /// </summary>
        public static string NotExistsRecord {
            get {
                return ResourceManager.GetString("NotExistsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values for field {0} are not equal..
        /// </summary>
        public static string ValuesNotEqualForField {
            get {
                return ResourceManager.GetString("ValuesNotEqualForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values for field {0} are not matched..
        /// </summary>
        public static string ValuesNotMatchForField {
            get {
                return ResourceManager.GetString("ValuesNotMatchForField", resourceCulture);
            }
        }
    }
}
