//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityValidations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityValidations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Identity.Resources.IdentityValidations", typeof(IdentityValidations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already has the role..
        /// </summary>
        public static string DuplicateRole {
            get {
                return ResourceManager.GetString("DuplicateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is already exist..
        /// </summary>
        public static string DuplicateUsername {
            get {
                return ResourceManager.GetString("DuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already verified..
        /// </summary>
        public static string EmailAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email can not be set for the user..
        /// </summary>
        public static string EmailCantSet {
            get {
                return ResourceManager.GetString("EmailCantSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The emailhas not been yet verified..
        /// </summary>
        public static string EmailNotVerified {
            get {
                return ResourceManager.GetString("EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assign date can not be in the future..
        /// </summary>
        public static string FutureAssignDate {
            get {
                return ResourceManager.GetString("FutureAssignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        public static string IncorrectUsernameOrPasseword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPasseword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not meet the minimum strength level defined..
        /// </summary>
        public static string InsufficientPasswordStrength {
            get {
                return ResourceManager.GetString("InsufficientPasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or verification key is invalid or has been expired..
        /// </summary>
        public static string InvalidEmailOrVerificationKey {
            get {
                return ResourceManager.GetString("InvalidEmailOrVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile or verification key is invalid or has been expired..
        /// </summary>
        public static string InvalidMobileOrVerificationKey {
            get {
                return ResourceManager.GetString("InvalidMobileOrVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile is already verified..
        /// </summary>
        public static string MobileAlreadyVerified {
            get {
                return ResourceManager.GetString("MobileAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile can not be set for the user..
        /// </summary>
        public static string MobileCantSet {
            get {
                return ResourceManager.GetString("MobileCantSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile has not been yet verified..
        /// </summary>
        public static string MobileNotVerified {
            get {
                return ResourceManager.GetString("MobileNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email set for the user to activate by..
        /// </summary>
        public static string NoEmailSet {
            get {
                return ResourceManager.GetString("NoEmailSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mobile set for the user to activate by..
        /// </summary>
        public static string NoMobileSet {
            get {
                return ResourceManager.GetString("NoMobileSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role is defined to assign to the permission..
        /// </summary>
        public static string NoRoleDefinedForPermission {
            get {
                return ResourceManager.GetString("NoRoleDefinedForPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role is defined to assign to the user..
        /// </summary>
        public static string NoRoleDefinedForUser {
            get {
                return ResourceManager.GetString("NoRoleDefinedForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not activated..
        /// </summary>
        public static string NotActiveUser {
            get {
                return ResourceManager.GetString("NotActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission does not belong to the role..
        /// </summary>
        public static string NotExistsPermissionForRole {
            get {
                return ResourceManager.GetString("NotExistsPermissionForRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role does not belong to the user..
        /// </summary>
        public static string NotExistsRoleForUser {
            get {
                return ResourceManager.GetString("NotExistsRoleForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is must be hashed..
        /// </summary>
        public static string PasswordNotHashed {
            get {
                return ResourceManager.GetString("PasswordNotHashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already activated..
        /// </summary>
        public static string UserAlreadyActivated {
            get {
                return ResourceManager.GetString("UserAlreadyActivated", resourceCulture);
            }
        }
    }
}
